name: Update scores and analyse
on: push    # TODO: maybe limit this once it's in master? Just the score file path?
env:
  # Allows us to call github APIs with our own personal auth token
  # eg. if we want to open issues as a result of Actions results - see more here:
  # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository, delete old results
        run: |
          git init
          # TODO: need to add the appropriate secret to the Github repo
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git fetch
          git checkout actions-automation
          rm -rf results/
      - name: Update scores etc
        run: |
          sudo apt-get update
          sudo apt-get install octave
          octave scripts/update.m
      - name: Push new results
        run: |
          ls -al
          git branch --set-upstream-to=origin/actions-automation
          git commit -a -m 'Recalculate totals and records'
          git push
