name: Update scores and analyse
on: push    # TODO: maybe limit this once it's in master? Just the score file path?
env:
  # Allows us to call github APIs with our own personal auth token
  # eg. if we want to open issues as a result of Actions results - see more here:
  # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: gnuoctave/octave:6.3.0
    steps:
      # TODO: does Ubuntu include octave?
      - name: Push changes after running update
        run: |
          git init
          # TODO: need to add the appropriate secret to the Github repo
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          octave scripts/update.m
          git commit -a -m 'Recalculate totals and records'
          git push
